"""create users and obligations tables

Revision ID: b3ce2a2bd889
Revises: 
Create Date: 2026-08-23 19:04:49.763365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b3ce2a2bd889'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('monthly_income', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('fixed_expenses', sa.Numeric(precision=12, scale=2), server_default='0.00', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='EGP', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('fixed_expenses >= 0', name='ck_users_fixed_expenses_non_negative'),
    sa.CheckConstraint('monthly_income >= 0', name='ck_users_monthly_income_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('obligations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('item_name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('monthly_installment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('term_months', sa.Integer(), nullable=False),
    sa.Column('due_day_of_month', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('source', sa.String(length=20), server_default='manual_entry', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("source IN ('manual_entry', 'chatbot_entry')", name='ck_obligations_source_allowed'),
    sa.CheckConstraint("status IN ('active', 'completed', 'late', 'defaulted')", name='ck_obligations_status_allowed'),
    sa.CheckConstraint('due_day_of_month >= 1 AND due_day_of_month <= 31', name='ck_obligations_due_day_of_month_range'),
    sa.CheckConstraint('monthly_installment_amount >= 0', name='ck_obligations_monthly_installment_amount_non_negative'),
    sa.CheckConstraint('term_months > 0', name='ck_obligations_term_months_positive'),
    sa.CheckConstraint('total_amount >= 0', name='ck_obligations_total_amount_non_negative'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obligations_user_id'), 'obligations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obligations_user_id'), table_name='obligations')
    op.drop_table('obligations')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
